[boss]
#需要注意的是，就算设置了参数，返回的数据也不一定是你需要的数据，因为boss会返回不符合的数据用来在页面展示，所以你还需要使用ai过滤数据
#城市列表,101250100,101280600,101250600
city_list = []
#薪资待遇 0:不限 402：3k以下 403：3k-5k 404：5k-10k 405：10k-20k 406：20k-50k 407：50k以上
salary=404
#求职类型 0：不限 1901：全职 1902：实习 1903：兼职
job_type=0
#岗位经验 0：不限 101：经验不限 102：应届生 103：1年以内 104：1-3年 105：3-5年 106：5-10年 107：10年以上
experience=0
#学历要求 0：不限(但是不填） 202：大专 203：本科 204：硕士 205：博士 206：高中 208：中专/中技 209：初中及以下
degree=[203]
#公司行业 详情观看IndustryList.json
industry=[]
#公司规模 0：不限 301：0-20人 302：20-99人 303：100-499人 304：500-999人 305：1000-9999人 306：10000人以上
scale=[]
#活跃情况，该条件将作为变量填入对比详情，你可以自行选择填入系统提示词或者你自己的输入内
active_situation = '一周以内活跃'
[51job]#不支持同平台的应届生平台，因为需要复杂的投递简历，单纯的数字化投递无法满足要求
test=1
[ai]
api_key=''
base_url=''
model=''
#我的简历详情，可以使用ai生成具体的简历详情，看你了，都用ai来做这个了也不需考虑
resume = ''
#岗位详情
job_info = "岗位的名字为：{jobName}，薪资详情为{salaryDesc}，岗位介绍为{postDescription}，要求的学历为{degreeName}，职位经验为{experienceName}，职位条件为{showSkills}，工作地点为{locationName}，需要的技能为{showSkills}，招聘者活跃情况为{activeTimeDesc}"
#对比提示词-岗位的介绍词
compare_prompt = "我的简历为{resume}，岗位详情为：{job_info}，我的意向城市为...，不希望离家太远，薪资要求...，对比岗位详情与我的简历情况，看看我能否胜任这个工作，如果匹配度答70%以上，请输出True，如果匹配度低于70%，请输出False，不需要有其他输出格式，请勿输出其他内容"
#对比系统提示词
compare_system_prompt = "对比岗位详情与用户的简历情况，如果用户提供简历符合岗位要求，请输出'True'，如果用户的简历不符合岗位要求，请输出'False'，不需要有其他输出格式，请勿输出其他内容"
#针对性提示词用于根据岗位介绍和你的简历写出针对性的介绍词
specific_prompt = "我的简历详情为{resume}，该岗位的详情为{job_info}，请根据岗位详情和简历内容，写出一个针对该岗位的自我介绍，让该岗位的招聘者能够快速了解我，不要提供电话和我名字的信息，请勿输出其他内容"
#针对性系统提示词用于定向输出
specific_system_prompt = "根据用户的简历输出一个针对该岗位的自我介绍，让该岗位的招聘者能够快速了解用户，请勿输出其他内容"